language: node_js

node_js:
  - "8"

notifications:
  email: false

install:
  - npm install
  - npm install -g codecov
  - npm install -g coveralls

before_script:
  - npm run build

script:
  - npm test && codecov && cat ./coverage/lcov.info | coveralls
