env:
  global:
    - CC_TEST_REPORTER_ID=b26939cc6d10b334bc7096829c6d2c8d31aea11ef6e7b8fde006595760e09a43

language: node_js

node_js:
  - "8"

notifications:
  email: false

install:
  - npm install
  - npm install -g codecov
  - npm install -g coveralls

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build

script:
  - npm test && codecov && cat ./coverage/lcov.info | coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  app: yet-another-wallet
  api_key:
    secure: cV9d7chQHba2Tv5nV4ByAy/rN5tADe3raj7LzEpnbkQHsCiG9qsTm9cPVn2BFF7Fhb3ZNqrmPfl1XU+M+xEkAzP/OqzpQ+1e90AdUzYP//XJotRMUw21c8PaMZMaPHE+JeSyLkPiwlsbpLZNLmk5aFW/JISe99PbdsnFjBef51FoJ0yjRyyRFzFgliS0dlod701j+biEqtVuRZx451LrKOa9Tevsis9LhjYj66w7o1yciUnPdwttEyjzjTkFlCMBx0KdzvfqHNKMpas150JIwRwV/22BlPonTU/fV4Tlfn2XWwCQOBxqJrK3+iL4nuSXbgpaG0EwNhzhxudHxHllAt/DDGeltB5CaQi8GZEy1d0N9ajsF8B9dl99RnOYpSGis/mYvzYAx/janE90kEf85hLsNM931sTbYQIc1QIiAiPEIkqRZbTVWzZeVnl/rG7KbCGIcoqPdwbufdVyqzIzBCGJx4THkFQpoe0xkN3mtHMpXNd+TyaMBSxZqas92h8XEFgnEMBj05vW7EjEB41dpcC2Coqk8es5OEXm9fcV4GxyvymH/jqaITvF7KFMS7A0RWyIk1cW/NxucJrWnVS5HXVSZMkmkYZQpEyfLgVUiYXL6aUkg+bG5ZWVCIoeKiUGMey0CoesrRdOR8BgnXEmButTpfdOnpxYp1x67Hey3mQ=
