env:
  global:
    - CC_TEST_REPORTER_ID=b26939cc6d10b334bc7096829c6d2c8d31aea11ef6e7b8fde006595760e09a43

language: node_js

node_js:
  - "8"

notifications:
  email: false

install:
  - npm install
  - npm install -g codecov
  - npm install -g coveralls

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build

script:
  - npm test && codecov && cat ./coverage/lcov.info | coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
